/*
 * This file is generated by jOOQ.
*/
package com.boot.jooq.tables.records;


import com.boot.jooq.tables.AppLogin;

import java.sql.Timestamp;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AppLoginRecord extends UpdatableRecordImpl<AppLoginRecord> implements Record6<UInteger, String, Timestamp, String, String, String> {

    private static final long serialVersionUID = -2035124979;

    /**
     * Setter for <code>wiza.app_login.id</code>.
     */
    public void setId(UInteger value) {
        set(0, value);
    }

    /**
     * Getter for <code>wiza.app_login.id</code>.
     */
    @NotNull
    public UInteger getId() {
        return (UInteger) get(0);
    }

    /**
     * Setter for <code>wiza.app_login.username</code>.
     */
    public void setUsername(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>wiza.app_login.username</code>.
     */
    @NotNull
    @Size(max = 50)
    public String getUsername() {
        return (String) get(1);
    }

    /**
     * Setter for <code>wiza.app_login.login_date</code>.
     */
    public void setLoginDate(Timestamp value) {
        set(2, value);
    }

    /**
     * Getter for <code>wiza.app_login.login_date</code>.
     */
    public Timestamp getLoginDate() {
        return (Timestamp) get(2);
    }

    /**
     * Setter for <code>wiza.app_login.ip_address</code>.
     */
    public void setIpAddress(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>wiza.app_login.ip_address</code>.
     */
    @NotNull
    @Size(max = 50)
    public String getIpAddress() {
        return (String) get(3);
    }

    /**
     * Setter for <code>wiza.app_login.message</code>.
     */
    public void setMessage(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>wiza.app_login.message</code>.
     */
    @NotNull
    @Size(max = 50)
    public String getMessage() {
        return (String) get(4);
    }

    /**
     * Setter for <code>wiza.app_login.user_agent</code>.
     */
    public void setUserAgent(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>wiza.app_login.user_agent</code>.
     */
    @Size(max = 250)
    public String getUserAgent() {
        return (String) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<UInteger> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<UInteger, String, Timestamp, String, String, String> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<UInteger, String, Timestamp, String, String, String> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field1() {
        return AppLogin.APP_LOGIN.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return AppLogin.APP_LOGIN.USERNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field3() {
        return AppLogin.APP_LOGIN.LOGIN_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return AppLogin.APP_LOGIN.IP_ADDRESS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return AppLogin.APP_LOGIN.MESSAGE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return AppLogin.APP_LOGIN.USER_AGENT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getUsername();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value3() {
        return getLoginDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getIpAddress();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getMessage();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getUserAgent();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AppLoginRecord value1(UInteger value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AppLoginRecord value2(String value) {
        setUsername(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AppLoginRecord value3(Timestamp value) {
        setLoginDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AppLoginRecord value4(String value) {
        setIpAddress(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AppLoginRecord value5(String value) {
        setMessage(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AppLoginRecord value6(String value) {
        setUserAgent(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AppLoginRecord values(UInteger value1, String value2, Timestamp value3, String value4, String value5, String value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AppLoginRecord
     */
    public AppLoginRecord() {
        super(AppLogin.APP_LOGIN);
    }

    /**
     * Create a detached, initialised AppLoginRecord
     */
    public AppLoginRecord(UInteger id, String username, Timestamp loginDate, String ipAddress, String message, String userAgent) {
        super(AppLogin.APP_LOGIN);

        set(0, id);
        set(1, username);
        set(2, loginDate);
        set(3, ipAddress);
        set(4, message);
        set(5, userAgent);
    }
}
