/*
 * This file is generated by jOOQ.
*/
package com.boot.jooq.tables.records;


import com.boot.jooq.tables.AppUserRole;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AppUserRoleRecord extends UpdatableRecordImpl<AppUserRoleRecord> implements Record2<UInteger, UInteger> {

    private static final long serialVersionUID = -1372362514;

    /**
     * Setter for <code>wiza.app_user_role.user_id</code>.
     */
    public void setUserId(UInteger value) {
        set(0, value);
    }

    /**
     * Getter for <code>wiza.app_user_role.user_id</code>.
     */
    @NotNull
    public UInteger getUserId() {
        return (UInteger) get(0);
    }

    /**
     * Setter for <code>wiza.app_user_role.role_id</code>.
     */
    public void setRoleId(UInteger value) {
        set(1, value);
    }

    /**
     * Getter for <code>wiza.app_user_role.role_id</code>.
     */
    @NotNull
    public UInteger getRoleId() {
        return (UInteger) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record2<UInteger, UInteger> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<UInteger, UInteger> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<UInteger, UInteger> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field1() {
        return AppUserRole.APP_USER_ROLE.USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field2() {
        return AppUserRole.APP_USER_ROLE.ROLE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value1() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value2() {
        return getRoleId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AppUserRoleRecord value1(UInteger value) {
        setUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AppUserRoleRecord value2(UInteger value) {
        setRoleId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AppUserRoleRecord values(UInteger value1, UInteger value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AppUserRoleRecord
     */
    public AppUserRoleRecord() {
        super(AppUserRole.APP_USER_ROLE);
    }

    /**
     * Create a detached, initialised AppUserRoleRecord
     */
    public AppUserRoleRecord(UInteger userId, UInteger roleId) {
        super(AppUserRole.APP_USER_ROLE);

        set(0, userId);
        set(1, roleId);
    }
}
