/*
 * This file is generated by jOOQ.
*/
package com.boot.jooq.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AppLogin implements Serializable {

    private static final long serialVersionUID = 1402729451;

    private UInteger  id;
    private String    username;
    private Timestamp loginDate;
    private String    ipAddress;
    private String    message;
    private String    userAgent;

    public AppLogin() {}

    public AppLogin(AppLogin value) {
        this.id = value.id;
        this.username = value.username;
        this.loginDate = value.loginDate;
        this.ipAddress = value.ipAddress;
        this.message = value.message;
        this.userAgent = value.userAgent;
    }

    public AppLogin(
        UInteger  id,
        String    username,
        Timestamp loginDate,
        String    ipAddress,
        String    message,
        String    userAgent
    ) {
        this.id = id;
        this.username = username;
        this.loginDate = loginDate;
        this.ipAddress = ipAddress;
        this.message = message;
        this.userAgent = userAgent;
    }

    @NotNull
    public UInteger getId() {
        return this.id;
    }

    public void setId(UInteger id) {
        this.id = id;
    }

    @NotNull
    @Size(max = 50)
    public String getUsername() {
        return this.username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public Timestamp getLoginDate() {
        return this.loginDate;
    }

    public void setLoginDate(Timestamp loginDate) {
        this.loginDate = loginDate;
    }

    @NotNull
    @Size(max = 50)
    public String getIpAddress() {
        return this.ipAddress;
    }

    public void setIpAddress(String ipAddress) {
        this.ipAddress = ipAddress;
    }

    @NotNull
    @Size(max = 50)
    public String getMessage() {
        return this.message;
    }

    public void setMessage(String message) {
        this.message = message;
    }

    @Size(max = 250)
    public String getUserAgent() {
        return this.userAgent;
    }

    public void setUserAgent(String userAgent) {
        this.userAgent = userAgent;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("AppLogin (");

        sb.append(id);
        sb.append(", ").append(username);
        sb.append(", ").append(loginDate);
        sb.append(", ").append(ipAddress);
        sb.append(", ").append(message);
        sb.append(", ").append(userAgent);

        sb.append(")");
        return sb.toString();
    }
}
