/*
 * This file is generated by jOOQ.
*/
package com.boot.jooq.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AppUser implements Serializable {

    private static final long serialVersionUID = -565638287;

    private UInteger id;
    private String   username;
    private String   password;
    private Boolean  active;
    private String   email;
    private String   firstName;
    private String   lastName;
    private String   phone;
    private UInteger companyId;

    public AppUser() {}

    public AppUser(AppUser value) {
        this.id = value.id;
        this.username = value.username;
        this.password = value.password;
        this.active = value.active;
        this.email = value.email;
        this.firstName = value.firstName;
        this.lastName = value.lastName;
        this.phone = value.phone;
        this.companyId = value.companyId;
    }

    public AppUser(
        UInteger id,
        String   username,
        String   password,
        Boolean  active,
        String   email,
        String   firstName,
        String   lastName,
        String   phone,
        UInteger companyId
    ) {
        this.id = id;
        this.username = username;
        this.password = password;
        this.active = active;
        this.email = email;
        this.firstName = firstName;
        this.lastName = lastName;
        this.phone = phone;
        this.companyId = companyId;
    }

    @NotNull
    public UInteger getId() {
        return this.id;
    }

    public void setId(UInteger id) {
        this.id = id;
    }

    @NotNull
    @Size(max = 50)
    public String getUsername() {
        return this.username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    @NotNull
    @Size(max = 100)
    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public Boolean getActive() {
        return this.active;
    }

    public void setActive(Boolean active) {
        this.active = active;
    }

    @Size(max = 100)
    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    @NotNull
    @Size(max = 50)
    public String getFirstName() {
        return this.firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    @NotNull
    @Size(max = 50)
    public String getLastName() {
        return this.lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    @NotNull
    @Size(max = 50)
    public String getPhone() {
        return this.phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public UInteger getCompanyId() {
        return this.companyId;
    }

    public void setCompanyId(UInteger companyId) {
        this.companyId = companyId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("AppUser (");

        sb.append(id);
        sb.append(", ").append(username);
        sb.append(", ").append(password);
        sb.append(", ").append(active);
        sb.append(", ").append(email);
        sb.append(", ").append(firstName);
        sb.append(", ").append(lastName);
        sb.append(", ").append(phone);
        sb.append(", ").append(companyId);

        sb.append(")");
        return sb.toString();
    }
}
