/*
 * This file is generated by jOOQ.
*/
package com.boot.jooq;


import com.boot.jooq.tables.AppLogin;
import com.boot.jooq.tables.AppRole;
import com.boot.jooq.tables.AppUser;
import com.boot.jooq.tables.AppUserRole;
import com.boot.jooq.tables.Company;
import com.boot.jooq.tables.SchemaVersion;
import com.boot.jooq.tables.User;
import com.boot.jooq.tables.records.AppLoginRecord;
import com.boot.jooq.tables.records.AppRoleRecord;
import com.boot.jooq.tables.records.AppUserRecord;
import com.boot.jooq.tables.records.AppUserRoleRecord;
import com.boot.jooq.tables.records.CompanyRecord;
import com.boot.jooq.tables.records.SchemaVersionRecord;
import com.boot.jooq.tables.records.UserRecord;

import javax.annotation.Generated;

import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.AbstractKeys;
import org.jooq.types.UInteger;


/**
 * A class modelling foreign key relationships between tables of the <code>wiza</code> 
 * schema
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<AppLoginRecord, UInteger> IDENTITY_APP_LOGIN = Identities0.IDENTITY_APP_LOGIN;
    public static final Identity<AppRoleRecord, UInteger> IDENTITY_APP_ROLE = Identities0.IDENTITY_APP_ROLE;
    public static final Identity<AppUserRecord, UInteger> IDENTITY_APP_USER = Identities0.IDENTITY_APP_USER;
    public static final Identity<CompanyRecord, UInteger> IDENTITY_COMPANY = Identities0.IDENTITY_COMPANY;
    public static final Identity<UserRecord, Integer> IDENTITY_USER = Identities0.IDENTITY_USER;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<AppLoginRecord> KEY_APP_LOGIN_PRIMARY = UniqueKeys0.KEY_APP_LOGIN_PRIMARY;
    public static final UniqueKey<AppRoleRecord> KEY_APP_ROLE_PRIMARY = UniqueKeys0.KEY_APP_ROLE_PRIMARY;
    public static final UniqueKey<AppRoleRecord> KEY_APP_ROLE_NAME = UniqueKeys0.KEY_APP_ROLE_NAME;
    public static final UniqueKey<AppUserRecord> KEY_APP_USER_PRIMARY = UniqueKeys0.KEY_APP_USER_PRIMARY;
    public static final UniqueKey<AppUserRecord> KEY_APP_USER_USERNAME = UniqueKeys0.KEY_APP_USER_USERNAME;
    public static final UniqueKey<AppUserRecord> KEY_APP_USER_EMAIL = UniqueKeys0.KEY_APP_USER_EMAIL;
    public static final UniqueKey<AppUserRoleRecord> KEY_APP_USER_ROLE_PRIMARY = UniqueKeys0.KEY_APP_USER_ROLE_PRIMARY;
    public static final UniqueKey<CompanyRecord> KEY_COMPANY_PRIMARY = UniqueKeys0.KEY_COMPANY_PRIMARY;
    public static final UniqueKey<SchemaVersionRecord> KEY_SCHEMA_VERSION_PRIMARY = UniqueKeys0.KEY_SCHEMA_VERSION_PRIMARY;
    public static final UniqueKey<UserRecord> KEY_USER_PRIMARY = UniqueKeys0.KEY_USER_PRIMARY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<AppUserRecord, CompanyRecord> APP_USER_IBFK_1 = ForeignKeys0.APP_USER_IBFK_1;
    public static final ForeignKey<AppUserRoleRecord, AppUserRecord> APP_USER_ROLE_IBFK_1 = ForeignKeys0.APP_USER_ROLE_IBFK_1;
    public static final ForeignKey<AppUserRoleRecord, AppRoleRecord> APP_USER_ROLE_IBFK_2 = ForeignKeys0.APP_USER_ROLE_IBFK_2;
    public static final ForeignKey<UserRecord, CompanyRecord> USER_IBFK_1 = ForeignKeys0.USER_IBFK_1;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 extends AbstractKeys {
        public static Identity<AppLoginRecord, UInteger> IDENTITY_APP_LOGIN = createIdentity(AppLogin.APP_LOGIN, AppLogin.APP_LOGIN.ID);
        public static Identity<AppRoleRecord, UInteger> IDENTITY_APP_ROLE = createIdentity(AppRole.APP_ROLE, AppRole.APP_ROLE.ID);
        public static Identity<AppUserRecord, UInteger> IDENTITY_APP_USER = createIdentity(AppUser.APP_USER, AppUser.APP_USER.ID);
        public static Identity<CompanyRecord, UInteger> IDENTITY_COMPANY = createIdentity(Company.COMPANY, Company.COMPANY.ID);
        public static Identity<UserRecord, Integer> IDENTITY_USER = createIdentity(User.USER, User.USER.ID);
    }

    private static class UniqueKeys0 extends AbstractKeys {
        public static final UniqueKey<AppLoginRecord> KEY_APP_LOGIN_PRIMARY = createUniqueKey(AppLogin.APP_LOGIN, "KEY_app_login_PRIMARY", AppLogin.APP_LOGIN.ID);
        public static final UniqueKey<AppRoleRecord> KEY_APP_ROLE_PRIMARY = createUniqueKey(AppRole.APP_ROLE, "KEY_app_role_PRIMARY", AppRole.APP_ROLE.ID);
        public static final UniqueKey<AppRoleRecord> KEY_APP_ROLE_NAME = createUniqueKey(AppRole.APP_ROLE, "KEY_app_role_name", AppRole.APP_ROLE.NAME);
        public static final UniqueKey<AppUserRecord> KEY_APP_USER_PRIMARY = createUniqueKey(AppUser.APP_USER, "KEY_app_user_PRIMARY", AppUser.APP_USER.ID);
        public static final UniqueKey<AppUserRecord> KEY_APP_USER_USERNAME = createUniqueKey(AppUser.APP_USER, "KEY_app_user_username", AppUser.APP_USER.USERNAME);
        public static final UniqueKey<AppUserRecord> KEY_APP_USER_EMAIL = createUniqueKey(AppUser.APP_USER, "KEY_app_user_email", AppUser.APP_USER.EMAIL);
        public static final UniqueKey<AppUserRoleRecord> KEY_APP_USER_ROLE_PRIMARY = createUniqueKey(AppUserRole.APP_USER_ROLE, "KEY_app_user_role_PRIMARY", AppUserRole.APP_USER_ROLE.USER_ID, AppUserRole.APP_USER_ROLE.ROLE_ID);
        public static final UniqueKey<CompanyRecord> KEY_COMPANY_PRIMARY = createUniqueKey(Company.COMPANY, "KEY_company_PRIMARY", Company.COMPANY.ID);
        public static final UniqueKey<SchemaVersionRecord> KEY_SCHEMA_VERSION_PRIMARY = createUniqueKey(SchemaVersion.SCHEMA_VERSION, "KEY_schema_version_PRIMARY", SchemaVersion.SCHEMA_VERSION.INSTALLED_RANK);
        public static final UniqueKey<UserRecord> KEY_USER_PRIMARY = createUniqueKey(User.USER, "KEY_user_PRIMARY", User.USER.ID);
    }

    private static class ForeignKeys0 extends AbstractKeys {
        public static final ForeignKey<AppUserRecord, CompanyRecord> APP_USER_IBFK_1 = createForeignKey(com.boot.jooq.Keys.KEY_COMPANY_PRIMARY, AppUser.APP_USER, "app_user_ibfk_1", AppUser.APP_USER.COMPANY_ID);
        public static final ForeignKey<AppUserRoleRecord, AppUserRecord> APP_USER_ROLE_IBFK_1 = createForeignKey(com.boot.jooq.Keys.KEY_APP_USER_PRIMARY, AppUserRole.APP_USER_ROLE, "app_user_role_ibfk_1", AppUserRole.APP_USER_ROLE.USER_ID);
        public static final ForeignKey<AppUserRoleRecord, AppRoleRecord> APP_USER_ROLE_IBFK_2 = createForeignKey(com.boot.jooq.Keys.KEY_APP_ROLE_PRIMARY, AppUserRole.APP_USER_ROLE, "app_user_role_ibfk_2", AppUserRole.APP_USER_ROLE.ROLE_ID);
        public static final ForeignKey<UserRecord, CompanyRecord> USER_IBFK_1 = createForeignKey(com.boot.jooq.Keys.KEY_COMPANY_PRIMARY, User.USER, "user_ibfk_1", User.USER.COMPANY_ID);
    }
}
