/*
 * This file is generated by jOOQ.
*/
package com.boot.jooq;


import com.boot.jooq.tables.AppLogin;
import com.boot.jooq.tables.AppRole;
import com.boot.jooq.tables.AppUser;
import com.boot.jooq.tables.AppUserRole;
import com.boot.jooq.tables.Company;
import com.boot.jooq.tables.SchemaVersion;
import com.boot.jooq.tables.User;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in wiza
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>wiza.app_login</code>.
     */
    public static final AppLogin APP_LOGIN = com.boot.jooq.tables.AppLogin.APP_LOGIN;

    /**
     * The table <code>wiza.app_role</code>.
     */
    public static final AppRole APP_ROLE = com.boot.jooq.tables.AppRole.APP_ROLE;

    /**
     * The table <code>wiza.app_user</code>.
     */
    public static final AppUser APP_USER = com.boot.jooq.tables.AppUser.APP_USER;

    /**
     * The table <code>wiza.app_user_role</code>.
     */
    public static final AppUserRole APP_USER_ROLE = com.boot.jooq.tables.AppUserRole.APP_USER_ROLE;

    /**
     * The table <code>wiza.company</code>.
     */
    public static final Company COMPANY = com.boot.jooq.tables.Company.COMPANY;

    /**
     * The table <code>wiza.schema_version</code>.
     */
    public static final SchemaVersion SCHEMA_VERSION = com.boot.jooq.tables.SchemaVersion.SCHEMA_VERSION;

    /**
     * The table <code>wiza.user</code>.
     */
    public static final User USER = com.boot.jooq.tables.User.USER;
}
