/*
 * This file is generated by jOOQ.
*/
package com.boot.jooq;


import com.boot.jooq.tables.AppLogin;
import com.boot.jooq.tables.AppRole;
import com.boot.jooq.tables.AppUser;
import com.boot.jooq.tables.AppUserRole;
import com.boot.jooq.tables.Company;
import com.boot.jooq.tables.SchemaVersion;
import com.boot.jooq.tables.User;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Wiza extends SchemaImpl {

    private static final long serialVersionUID = 2046799460;

    /**
     * The reference instance of <code>wiza</code>
     */
    public static final Wiza WIZA = new Wiza();

    /**
     * The table <code>wiza.app_login</code>.
     */
    public final AppLogin APP_LOGIN = com.boot.jooq.tables.AppLogin.APP_LOGIN;

    /**
     * The table <code>wiza.app_role</code>.
     */
    public final AppRole APP_ROLE = com.boot.jooq.tables.AppRole.APP_ROLE;

    /**
     * The table <code>wiza.app_user</code>.
     */
    public final AppUser APP_USER = com.boot.jooq.tables.AppUser.APP_USER;

    /**
     * The table <code>wiza.app_user_role</code>.
     */
    public final AppUserRole APP_USER_ROLE = com.boot.jooq.tables.AppUserRole.APP_USER_ROLE;

    /**
     * The table <code>wiza.company</code>.
     */
    public final Company COMPANY = com.boot.jooq.tables.Company.COMPANY;

    /**
     * The table <code>wiza.schema_version</code>.
     */
    public final SchemaVersion SCHEMA_VERSION = com.boot.jooq.tables.SchemaVersion.SCHEMA_VERSION;

    /**
     * The table <code>wiza.user</code>.
     */
    public final User USER = com.boot.jooq.tables.User.USER;

    /**
     * No further instances allowed
     */
    private Wiza() {
        super("wiza", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            AppLogin.APP_LOGIN,
            AppRole.APP_ROLE,
            AppUser.APP_USER,
            AppUserRole.APP_USER_ROLE,
            Company.COMPANY,
            SchemaVersion.SCHEMA_VERSION,
            User.USER);
    }
}
