/*
 * This file is generated by jOOQ.
*/
package com.boot.jooq.tables;


import com.boot.jooq.Keys;
import com.boot.jooq.Wiza;
import com.boot.jooq.tables.records.AppLoginRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AppLogin extends TableImpl<AppLoginRecord> {

    private static final long serialVersionUID = 1411113585;

    /**
     * The reference instance of <code>wiza.app_login</code>
     */
    public static final AppLogin APP_LOGIN = new AppLogin();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AppLoginRecord> getRecordType() {
        return AppLoginRecord.class;
    }

    /**
     * The column <code>wiza.app_login.id</code>.
     */
    public final TableField<AppLoginRecord, UInteger> ID = createField("id", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>wiza.app_login.username</code>.
     */
    public final TableField<AppLoginRecord, String> USERNAME = createField("username", org.jooq.impl.SQLDataType.VARCHAR.length(50).nullable(false), this, "");

    /**
     * The column <code>wiza.app_login.login_date</code>.
     */
    public final TableField<AppLoginRecord, Timestamp> LOGIN_DATE = createField("login_date", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.inline("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * The column <code>wiza.app_login.ip_address</code>.
     */
    public final TableField<AppLoginRecord, String> IP_ADDRESS = createField("ip_address", org.jooq.impl.SQLDataType.VARCHAR.length(50).nullable(false), this, "");

    /**
     * The column <code>wiza.app_login.message</code>.
     */
    public final TableField<AppLoginRecord, String> MESSAGE = createField("message", org.jooq.impl.SQLDataType.VARCHAR.length(50).nullable(false), this, "");

    /**
     * The column <code>wiza.app_login.user_agent</code>.
     */
    public final TableField<AppLoginRecord, String> USER_AGENT = createField("user_agent", org.jooq.impl.SQLDataType.VARCHAR.length(250), this, "");

    /**
     * Create a <code>wiza.app_login</code> table reference
     */
    public AppLogin() {
        this("app_login", null);
    }

    /**
     * Create an aliased <code>wiza.app_login</code> table reference
     */
    public AppLogin(String alias) {
        this(alias, APP_LOGIN);
    }

    private AppLogin(String alias, Table<AppLoginRecord> aliased) {
        this(alias, aliased, null);
    }

    private AppLogin(String alias, Table<AppLoginRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Wiza.WIZA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<AppLoginRecord, UInteger> getIdentity() {
        return Keys.IDENTITY_APP_LOGIN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<AppLoginRecord> getPrimaryKey() {
        return Keys.KEY_APP_LOGIN_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<AppLoginRecord>> getKeys() {
        return Arrays.<UniqueKey<AppLoginRecord>>asList(Keys.KEY_APP_LOGIN_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AppLogin as(String alias) {
        return new AppLogin(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public AppLogin rename(String name) {
        return new AppLogin(name, null);
    }
}
