/*
 * This file is generated by jOOQ.
*/
package com.boot.jooq.tables;


import com.boot.jooq.Keys;
import com.boot.jooq.Wiza;
import com.boot.jooq.tables.records.AppUserRoleRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AppUserRole extends TableImpl<AppUserRoleRecord> {

    private static final long serialVersionUID = -61180109;

    /**
     * The reference instance of <code>wiza.app_user_role</code>
     */
    public static final AppUserRole APP_USER_ROLE = new AppUserRole();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AppUserRoleRecord> getRecordType() {
        return AppUserRoleRecord.class;
    }

    /**
     * The column <code>wiza.app_user_role.user_id</code>.
     */
    public final TableField<AppUserRoleRecord, UInteger> USER_ID = createField("user_id", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>wiza.app_user_role.role_id</code>.
     */
    public final TableField<AppUserRoleRecord, UInteger> ROLE_ID = createField("role_id", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

    /**
     * Create a <code>wiza.app_user_role</code> table reference
     */
    public AppUserRole() {
        this("app_user_role", null);
    }

    /**
     * Create an aliased <code>wiza.app_user_role</code> table reference
     */
    public AppUserRole(String alias) {
        this(alias, APP_USER_ROLE);
    }

    private AppUserRole(String alias, Table<AppUserRoleRecord> aliased) {
        this(alias, aliased, null);
    }

    private AppUserRole(String alias, Table<AppUserRoleRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Wiza.WIZA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<AppUserRoleRecord> getPrimaryKey() {
        return Keys.KEY_APP_USER_ROLE_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<AppUserRoleRecord>> getKeys() {
        return Arrays.<UniqueKey<AppUserRoleRecord>>asList(Keys.KEY_APP_USER_ROLE_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<AppUserRoleRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<AppUserRoleRecord, ?>>asList(Keys.APP_USER_ROLE_IBFK_1, Keys.APP_USER_ROLE_IBFK_2);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AppUserRole as(String alias) {
        return new AppUserRole(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public AppUserRole rename(String name) {
        return new AppUserRole(name, null);
    }
}
